config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to:'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

 

  get '/alumni' => 'home#alumni'  
  get '/about' => 'home#about'
  get '/index' => 'home#index'  
    resources  :home
  root to: 'home#index'
  devise_for :userlogins
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/userlogin.rb
class Userlogin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |userlogin|
      userlogin.provider = auth.provider 
      userlogin.uid      = auth.uid
      userlogin.name     = auth.info.name
      userlogin.oauth_token = auth.credentials.token
      userlogin.oauth_expires_at = Time.at(auth.credentials.expires_at)
      userlogin.save!
    end
  end  

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    alumni_path
  end

private
  def current_user
    @current_user ||= Userlogin.find(session[:userlogin_id]) if session[:userlogin_id]
  end
  helper_method :current_user

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def alumni
  end

  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    userlogin = Userlogin.from_omniauth(env["omniauth.auth"])
    session[:userlogin_id] = userlogin.id
    redirect_to "/alumni"
  end
  def destroy
    session[:userlogin_id] = nil
    redirect_to "/index"
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/about.html.erb
 
 <meta charset="UTF-8">
  <meta name=viewport content="width=device-width, initial-scale=1">
  <meta name="description" content="Free Web tutorials">
  <meta name="keywords" content="HTML5,CSS,JavaScript">
  <meta name="author" content="Hege Refsnes">
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link href="../../assets/index.scss" rel="stylesheet">
  <link href="../../assets/about.scss" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js" type="text/javascript"></script>  


  <div class=" page31" > 
    <div class="status"></div>    
    <div class="container">    
      <nav class="navbar navbar-default">
        <div class="container-fluid">        
          <div class="navbar-header"> 
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              </button>  
            <a href="#"> <%= image_tag("icons/talentspace1.png", class:"img-responsive main-icon") %></a>         
              
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">              
              <li><a href="/index">HOME</a></li>
              <li><a href="/alumni">ALUMNI</a></li>
              <li><a href="#">ABOUT</a></li>             
              <% if userlogin_signed_in? %>
                <li><a data-method="delete" href="/userlogins/sign_out">SIGN OUT</a>       
              <% elsif current_user %>
                Signed in as <strong><%= current_user.name %></strong>
                <li><a href="/signout">SIGNOUT</a>
              <% else %>        
                <li> <a href="#myLogin"  data-toggle="modal">SIGN IN</a></li>
              <% end %>
            </ul>
          </div> 
        </div>       
      </nav>

      <div class="col-md-12 text-center">
        <h2>About</h2>
        <h3>TalentSpace is a venture to fill the gap between people who are passionate about programming and software industry. We provide training and mentorship in latest technologies.</h3>        
        <div class="col-md-12 brder">
          <h3>We are currently located at K.R Puram, Bangalore.</h3>
        </div>
        <div class="col-md-12">
          <h2>Trainer Profiles</h2>
        </div>
      </div>

      <div class="col-md-12 abt">
        <div class="col-md-3">
          <%= image_tag("img/sajin1.png", class:"img-responsive trainer-image") %>
        </div>
        <div class="col-md-9">
          <h4>Sajin M Prasad</h4>
          <p>
            Sajin M P is a Software Developer from Kerala. He's interested in technology, entrepreneurship and learning new things together.
          </p>
          <p>
            Currently he lives in Bangalore while working remotely for 
            <a href="http://foofys.com/">foOfys   </a>,
            an India based software services company. Earlier, he worked for
            <a href="http://bangthetable.com">Bang the Table</a>
             building 
            <a href="http://engagementhq.com">Community Engagement</a>
            solutions for State and National Governments of Australia, New Zealand and Canada.
          </p>
          <p>
            He's a volunteer at 
            <a href="http://smc.org.in">Swathanthra Malayalam Computing.</a>
             He has participated in 
            <a href="https://www.google-melange.com">Google Summer of Code</a> 
            for the same organization.
          </p>
          <p>
            He loves programming, traveling and photography. He pushes code to 
            <a href="https://github.com">GitHub</a>,
            tweets through @ershus and you can find his resume here.
          </p>
          <p>Email: <a href="mailto:sajin@foofys.com">sajin@foofys.com</a></p>
          <p>Blog: <a href="http://sajinmp.in/">sajinmp.in</a> </p>
        </div>
      </div>

      
      <footer class='footer'>
        <div class='pull-right'>
          <p class='footer-text'>
            Made with ♥ in
            <a target="_blank" href="https://en.wikipedia.org/wiki/Kochi">Kochi</a>
          </p>
        </div>
        <p>© TalentSpace 2015</p>
      </footer>




    </div>
  </div>
  

app/views/home/alumni.html.erb
 
 <meta charset="UTF-8">
  <meta name=viewport content="width=device-width, initial-scale=1">
  <meta name="description" content="Free Web tutorials">
  <meta name="keywords" content="HTML5,CSS,JavaScript">
  <meta name="author" content="Hege Refsnes">
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link href="../../assets/index.scss" rel="stylesheet">
  <link href="../../assets/alumni.scss" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js" type="text/javascript"></script>  


  <div class=" page21" > 
    <div class="status"></div>    
    <div class="container">    
      <nav class="navbar navbar-default">
        <div class="container-fluid">        
          <div class="navbar-header"> 
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              </button>  
            <a href="#"> <%= image_tag("icons/talentspace1.png", class:"img-responsive main-icon") %></a>         
              
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">              
              <li><a href="/index">HOME</a></li>
              <li><a href="#">ALUMNI</a></li>
              <li><a href="/about">ABOUT</a></li>              
              <% if userlogin_signed_in? %>
                <li><a data-method="delete" href="/userlogins/sign_out">SIGN OUT</a>       
              <% elsif current_user %>
                Signed in as <strong><%= current_user.name %></strong>
                <li><a id="sign_out" href="/signout">SIGNOUT</a>
              <% else %>        
                <li> <a href="#myLogin"  data-toggle="modal">SIGN IN</a></li>
              <% end %>
            </ul>
          </div> 
        </div>       
      </nav>

      <div class="col-md-12 text-center">
        <h2>Alumni</h2>        
      </div>
      <div class="row student1 text-center">
        <div class="col-md-4">
          <%= image_tag("alumni/rajeesh.png", class:"img-responsive alumni-image") %>
          <h4>Rajeesh</h4>
          <div class='social-links'>           
            <a target="_blank" class="btn btn-social-icon btn-linkedin" href="https://www.linkedin.com"><span class='fa fa-linkedin'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-github" href="https://github.com"><span class='fa fa-github'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-twitter" href="https://twitter.com"><span class='fa fa-twitter'></span>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <%= image_tag("alumni/sebin2.png", class:"img-responsive alumni-image") %>
          <h4>Sebin</h4>
          <div class='social-links'>           
            <a target="_blank" class="btn btn-social-icon btn-linkedin" href="https://www.linkedin.com"><span class='fa fa-linkedin'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-github" href="https://github.com"><span class='fa fa-github'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-twitter" href="https://twitter.com"><span class='fa fa-twitter'></span>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <%= image_tag("alumni/vikram2.png", class:"img-responsive alumni-image") %>
          <h4>Vikram</h4>
          <div class='social-links'>           
            <a target="_blank" class="btn btn-social-icon btn-linkedin" href="https://www.linkedin.com"><span class='fa fa-linkedin'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-github" href="https://github.com"><span class='fa fa-github'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-twitter" href="https://twitter.com"><span class='fa fa-twitter'></span>
            </a>
          </div>
        </div>
      </div> 
      <div class="row student2 text-center"> 
        <div class="col-md-4">
          <%= image_tag("alumni/rajeesh.png", class:"img-responsive alumni-image") %>
          <h4>Rajeesh</h4>
          <div class='social-links'>           
            <a target="_blank" class="btn btn-social-icon btn-linkedin" href="https://www.linkedin.com"><span class='fa fa-linkedin'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-github" href="https://github.com"><span class='fa fa-github'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-twitter" href="https://twitter.com"><span class='fa fa-twitter'></span>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <%= image_tag("alumni/sebin2.png", class:"img-responsive alumni-image") %>
          <h4>Sebin</h4>
          <div class='social-links'>           
            <a target="_blank" class="btn btn-social-icon btn-linkedin" href="https://www.linkedin.com"><span class='fa fa-linkedin'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-github" href="https://github.com"><span class='fa fa-github'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-twitter" href="https://twitter.com"><span class='fa fa-twitter'></span>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <%= image_tag("alumni/vikram2.png", class:"img-responsive alumni-image") %>
          <h4>Vikram</h4>
          <div class='social-links'>           
            <a target="_blank" class="btn btn-social-icon btn-linkedin" href="https://www.linkedin.com"><span class='fa fa-linkedin'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-github" href="https://github.com"><span class='fa fa-github'></span>
            </a>
            <a target="_blank" class="btn btn-social-icon btn-twitter" href="https://twitter.com"><span class='fa fa-twitter'></span>
            </a>
          </div>
        </div>
      </div> 
      <footer class='footer'>
        <div class='pull-right'>
          <p class='footer-text'>
            Made with ♥ in
            <a target="_blank" href="https://en.wikipedia.org/wiki/Kochi">Kochi</a>
          </p>
        </div>
        <p>© TalentSpace 2015</p>
      </footer>
    </div>
  </div>
  

app/views/home/index.html.erb
 
  <meta charset="UTF-8">
  <meta name=viewport content="width=device-width, initial-scale=1">
  <meta name="description" content="Free Web tutorials">
  <meta name="keywords" content="HTML5,CSS,JavaScript">
  <meta name="author" content="Hege Refsnes">
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link href="../../assets/index.scss" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js" type="text/javascript"></script>  


  <div class="jumbotron page1" > 
    <div class="status"></div>    
    <div class="container">    
      <nav class="navbar navbar-default">
        <div class="container-fluid">        
          <div class="navbar-header"> 
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              </button>  
            <a href="#"> <%= image_tag("icons/talentspace1.png", class:"img-responsive main-icon") %></a>         
              
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <div class=" video-link medium-paragraph text-center"> 
            <ul class="nav navbar-nav navbar-right">  
              <li><a href="#">HOME</a></li>
              
               <% if userlogin_signed_in? %>
                <li><a href="/alumni">ALUMNI</a></li>
                <li><a href="/about">ABOUT</a></li>
                <li><a data-method="delete" href="/userlogins/sign_out">SIGN OUT</a>       
              <% elsif current_user %>
                <li><a href="/alumni">ALUMNI</a></li>
                <li><a href="/about">ABOUT</a></li>
                Signed in as <strong><%= current_user.name %></strong>
                <li><a id="sign_out" href="/signout">SIGNOUT</a>
              <% else %> 
                <li><a href="/userlogins/sign_in">ALUMNI</a></li>
                <li><a href="/userlogins/sign_in">ABOUT</a></li>       
                <li> <a href="/userlogins/sign_in">SIGN IN</a></li>
              <% end %>
              </div>             
            </ul>
          </div> 
        </div>       
      </nav>
      <div class="row">
        <div class="col-md-5 ">
          <a href="#"> <%= image_tag("gif/giphy2.gif", class:"img-responsive main-icon") %></a>          
        </div>
        <div class="col-md-7">
          <h1>Professional Ruby on Rails Training</h1>
          <p>Learn how to build beautifully crafted web applications with Ruby on Rails and get hired by top companies</p>
          <% if userlogin_signed_in? %>
                   
          <% elsif current_user %>
            
          <% else %>    
            <div class="col-md-6 social-button">                          
                <a href="/auth/facebook" class="btn btn-block btn-social btn-facebook" id="sign_in">
                  <span class="fa fa-facebook"></span> Start with Facebook
                </a>                         
            </div> 
            <div class="col-md-6 social-button2">              
                <a  href="/auth/google_oauth2" class="btn btn-block btn-social btn-google" id="googleplus">
                  <span class="fa fa-google-plus"></span> Start with Google
                </a>                
            </div>
          <% end %>
          <div class="col-md-12 terms"> 
            <p class="para">
              By starting, you agree to HackerEarth's 
              <a class="conditions" href="#">Terms of Service </a> 
              and 
              <a class="conditions" href="#">Privacy Policy </a> 
            </p> 
          </div>
        </div>       
      </div>

      <div class="col-md-12 video-link medium-paragraph text-center">     
        <a href="#myModal"  data-toggle="modal">
          <span class="video-link-icon"><i class="fa fa-play-circle"></i></span> 
          <span class="video-link-text">LEARN HOW</span>
        </a>
      </div> 
      <div id="myModal" class="modal fade">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>                  
            </div>
            <div class="modal-body">
              <iframe id="learnHow" width="560" height="315" src="https://www.youtube.com/v/BI_VnnOLSKY"    allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen"></iframe>                  
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class=" page2">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h2>What you will learn</h2>
        </div>
        <div class="col-md-12">
          <div class="col-md-6">
            <h3>Shell Scripting</h3>
            <p>Learn all necessary commands and configurations. Understand bash syntax to write scripts</p>
          </div>
          <div class="col-md-6">
            <h3>Ruby on Rails</h3>
            <p>Build Web applications and RESTful APIs with Ruby on Rails. Learn essentials of HTML, CSS and JavaScript.</p>
          </div>
        </div>
        <div class="col-md-12">  
          <div class="col-md-6">
            <h3>Version control with Git</h3>
            <p>Track source code changes using Git. Learn collaborative development using GitHub.</p>
          </div>
          <div class="col-md-6">
            <h3>Project management</h3>
            <p>Know about various project management tools and methodologies.</p>
          </div>
        </div>
        <div class="col-md-12">  
           <div class="col-md-6">
            <h3>Programming in Ruby</h3>
            <p>Learn ruby and solve interesting problems.</p>
          </div>
          <div class="col-md-6">
            <h3>Production deployment</h3>
            <p>Configure and deploy applications in production server.</p>
          </div>
        </div>
      </div>
    </div>    
  </div>

  <div class=" page3">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h3>Partner Companies</h3>
          <div class="col-md-12">
            <div class="col-md-3">
              <a target="_blank" href="http://bigbinary.com"><%= image_tag("companies/bigbinary.png", class:"img-responsive main-icon bigb") %></a>
            </div>
            <div class="col-md-3">
              <a target="_blank" href="http://bangthetable.com"><%= image_tag("companies/bangthetable.jpg", class:"img-responsive main-icon bttable") %></a>
            </div>
            <div class="col-md-3">
              <a target="_blank" href="http://nilenso.com"><%= image_tag("companies/nilenso.png", class:"img-responsive main-icon nilenso") %></a>
            </div>
            <div class="col-md-3">
              <a target="_blank" href="http://hashcube.com"><%= image_tag("companies/hashcube.png", class:"img-responsive main-icon hashcube") %></a>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-3">
              <a target="_blank" href="http://chillr.in"><%= image_tag("companies/chillr.jpg", class:"img-responsive main-icon chillr") %></a>
            </div>
            <div class="col-md-3">
              <a data-toggle="tab" href="http://lookup.to"><%= image_tag("companies/lookup.jpg", class:"img-responsive main-icon lookup") %></a>
            </div>
            <div class="col-md-3">
              <a target="_blank" href="http://vibeapp.co"><%= image_tag("companies/vibe.png", class:"img-responsive main-icon vibe") %></a>
            </div>
            <div class="col-md-3">
              <a target="_blank" href="http://locus.sh"><%= image_tag("companies/locus.png", class:"img-responsive main-icon vibe") %></a>
            </div>
          </div>
          <div class="col-md-12">
            <div class="col-md-3 col-md-offset-3">
              <a target="_blank" href="http://multunus.com"><%= image_tag("companies/multunus.png", class:"img-responsive main-icon multunus") %></a>
            </div>
            <div class="col-md-3">
              <a target="_blank" href="http://aeroleads.com"><%= image_tag("companies/aeroleads.png", class:"img-responsive main-icon aeroleads") %></a>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-md-offset-3 text-center quote">
          <blockquote>
            What we’re looking for are open-minded developers who are keen to learn and solve problems, and want to share their curiosity with us.
            <cite>Deepa Venkatraman, Nilenso.</cite>
          </blockquote>
        </div>

        <footer class='footer'>
          <div class='pull-right'>
            <p class='footer-text'>
              Made with ♥ in
              <a target="_blank" href="https://en.wikipedia.org/wiki/Kochi">Kochi</a>
            </p>
          </div>
          <p>© TalentSpace 2015</p>
        </footer>
      </div>
    </div>  
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>